language: java

sudo: required

before_install:
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install virtualbox -qq --fix-missing

before_script:
  - which vboxmanage
  - vboxmanage --help

script:
  - mvn verify

after_script:
  - echo "This is the message body" | mutt -a /home/travis/build/barclay-reg/vagrant-maven-plugin/target/it/projects/all/build.log -s "subject of message" VAR_EMAIL
