language: java

sudo: required

before_install:
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install virtualbox -qq --fix-missing

before_script:
  - which vboxmanage
  - vboxmanage --help

script:
  - mvn verify
