language: java

sudo: required

before_install:
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install virtualbox -qq --fix-missing

before_script:
  - vboxmanage --help

script:
  - mvn verify

after_script:
  - for f in /home/travis/build/barclay-reg/vagrant-maven-plugin/target/it/projects/*/build.log; do echo "Showing $f file.."; cat $f done
  - cat /home/travis/build/barclay-reg/vagrant-maven-plugin/target/it/projects/*/build.log
