language: java

sudo: required

before_install:
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install virtualbox -qq --fix-missing
  - sudo apt-get install virtualbox-ose-dkms -q
  - sudo apt-get install linux-headers-generic -q
  - sudo dpkg-reconfigure virtualbox-dkms
  - sudo /etc/init.d/vboxdrv setup

before_script:
  - which vboxmanage
  - vboxmanage --help
  
script:
  - mvn verify
